data_preparation:
  data_formatter: PngFormatter


data_splitting:
  batch_size: 32
  color_mode: rgb
  image_size:
  - 256
  - 256
  shuffle: true
  train_seed: 0
  valid_seed: 42
  validation_split: 0.2


data_train_preprocessing:
  transformations:
  - name: Rescaling
    scale: 0.00392156862745098 # 1.0 / 2555
  - name: RandomFlip
    mode: horizontal_and_vertical
  - name: RandomRotation
    factor: 0.2


data_valid_preprocessing:
  transformations:
  - name: Rescaling
    scale: 0.00392156862745098 # 1.0 / 2555


model_evaluation:
  batch_size: 32


model_training:
  experiment: new-exp-test-5
  run_name: a_name

  compiler:
    loss: sparse_categorical_crossentropy
    metrics:
    - accuracy
    optimizer: RMSprop
  input_shape:
    image_height: 256
    image_width: 256
    n_channels: 3

  model_cfg:
  - name: Conv2D
    activation: relu
    filters: 32
    kernel_size: 3
    padding: same
    strides: 2
  - name: BatchNormalization
  - name: MaxPooling2D
    pool_size:
    - 2
    - 2
  - name: BatchNormalization
  - name: Conv2D
    activation: relu
    filters: 64
    kernel_size: 3
    padding: same
    strides: 1
  - name: BatchNormalization
  - name: MaxPooling2D
    pool_size:
    - 2
    - 2
  - name: BatchNormalization
  - name: Conv2D
    activation: relu
    filters: 128
    kernel_size: 3
    padding: same
    strides: 1
  - name: BatchNormalization
  - name: MaxPooling2D
    pool_size:
    - 2
    - 2
  - name: BatchNormalization
  - name: Flatten
  - name: Dense
    activation: relu
    units: 256
  - name: BatchNormalization
  - name: Dropout
    rate: 0.5
  - name: Dense
    activation: softmax
    units: 10

  training_cfg:
    batch_size: 32
    epochs: 1

